routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'web'], function () {

            Auth::routes();

            Route::group([
                'prefix' => '',
                'middleware' => ['auth']
                // 'middleware' => ['role:telco.*'],
            ], function() {
                    Route::resource('member', 'MemberController', [
                        'only' => ['index','create','store','edit','update','destroy']
                    ]);
                    Route::resource('user', 'UserController', [
                        'only' => ['index','create','store','edit','update','destroy']
                    ]);
                    Route::resource('testimony', 'TestimonyController');
                }
            );
        }
    );

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait; // add this trait to your user model

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username','email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Yajra\Datatables\Datatables;
use Hash;

use App\User;

class UserController extends Controller
{
    /**
     * @param User $user
     * 
     * @return void
     */

    public function __construct(User $user){
        $this->user = $user;

        // $this->middleware('role:telco.admin', ['only' => ['create', 'store','edit','update','destroy']]);
        // $this->middleware('role:telco.admin|telco.user', ['only' => ['index']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $user = $this->user->get();
            return Datatables::of($user)->make(true);
        }
        return view('pages.user.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User();
        return view('pages.user.create', compact('user') );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, User $user)
    {
        $request->validate( [
            'name' => 'required|string|max:255',
            'username' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6',
        ]);

        $user->create([
            'name' => $request->name, 
            'username' => $request->username,
            'email' => $request->email,
            'password' => Hash::make($request->password)
        ]);

        return view('pages.user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('pages.user.edit', compact('user') );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate( [
            'name' => 'required|string|max:255',
            'username' => 'required|string|max:255',
            'email' => 'required|string|email|max:255',
            'password' => 'required|string|min:6',
        ]);

        $user->update([
            'name' => $request->name, 
            'username' => $request->username,
            'email' => $request->email,
            'password' => Hash::make($request->password)
        ]);

        return view('pages.user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return response()->json([
			"success" => "true",
			"message" => "User has been has been deleted.",
		]);
    }
}

resources/views/pages/user/create.blade.php
@extends('adminlte::page')

@section('title','JMCIM Webapp')

@section('content_header')
<h1>JMCIM <small>Add User</small></h1>
@endsection

@section('content')
    <div class="box box-default">
        <div class="box-body">
            <div class="row">
                <div class="col-xs-12">
                    @include('layouts/error_box')
                    {{ Form::model($user, ['route' => ['user.store',$user->id], 'method' => 'POST', 'class' => 'form-horizontal'])}}
                    {{ csrf_field() }}

                    @include('pages.user.partials.forms')
                    <div class="form-group">
                        <div class="col-xs-1 col-xs-offset-2">
                            <button type="submit" class="btn btn-primary" placeholder"Submit"><i class="glyphicon glyphicon-check"></i> Save</button>
                        </div>
                        <div class="col-xs-1">
                            <a href="{{ route('user.index') }}" title="Cancel" class="btn btn-primary cancel_btn">
                            <i class="glyphicon glyphicon-remove-circle"></i> Cancel
                            </a>
                        </div>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
<script src="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.js') }}"></script>
@endsection

resources/views/pages/user/edit.blade.php
@extends('adminlte::page')

@section('title','JMCIM Webapp')

@section('content_header')
    <h1>JMCIM <small>Edit User</small></h1>
@endsection

@section('css')
<link rel="stylesheet"
          href="{{ asset('css/app.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/fonts/font_roboto/roboto.css') }}">

@endsection

@section('content')    
<div class="box box-default">
        <div class="box-body">
            <div class="row">
                <div class="col-xs-12">
                    @include('layouts/error_box')
                    {{ Form::model($user, ['route' => ['user.update',$user->id], 'method' => 'PUT', 'class' => 'form-horizontal'])}}
                    {{ csrf_field() }}

                    @include('pages.user.partials.forms')
                    <div class="form-group">
                        <div class="col-xs-1 col-xs-offset-2">
                            <button type="submit" class="btn btn-primary" placeholder"Submit"><i class="glyphicon glyphicon-check"></i> Save</button>
                        </div>
                        <div class="col-xs-1">
                            <a href="{{ route('user.index') }}" title="Cancel" class="btn btn-primary cancel_btn">
                            <i class="glyphicon glyphicon-remove-circle"></i> Cancel
                            </a>
                        </div>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
<script src="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.js') }}"></script>
@endsection

resources/views/pages/user/index.blade.php
@extends('adminlte::page')

@section('title','JMCIM Webapp')

@section('content_header')
    <h1>JMCIM<small>User</small></h1>
@endsection

@section('css')
    <link rel="stylesheet"
          href="{{ asset('css/app.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/fonts/font_roboto/roboto.css') }}">

@endsection

@section('content')
    <div class="box box-default">
        <div class="box-body">
            <div class="row">
                <div class="col-xs-12">
                    @include('layouts/error_box')

                    <a href="{{ route('user.create') }}" title="Add New" class="btn btn-primary btn-xs">
                        <i class="glyphicon glyphicon-plus"></i>Add New
                    </a>
                    <br></br>

                    <div class="table-responsive">
                    <table class="table table-striped" id="data-table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Username</th>
                                <th>Email</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
	<script src="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            var dataTable = $('#data-table').DataTable({
                processing: true,
                serverSide: true,
                deferRender: true,
                ajax: '{{ route("user.index") }}',
                columnDefs: [
                    {
                        'targets': 0,
                        'data': 'id',
                        'name': 'id',
                    },
                    {
                        'targets': 1,
                        'data': 'name',
                        'name': 'name',
                    },
                    {
                        'targets': 2,
                        'data': 'username',
                        'name': 'username',
                    },
                    {
                        'targets': 3,
                        'data': 'email',
                        'name': 'email',
                    },
                    {
                        'targets': 4,
                        'searchable': false,
                        'sortable': false,
                        'render': function(data,type,row){
                            var url = '{{ route('user.edit',':id') }}'.replace(':id',row.id);

                           		return [
								'<a href="' + url + '" title="Edit" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-edit"></i> Edit</a>' + " " +
								'<button data-id="' + row.id + '" type="button" title="Delete" class="btn btn-danger btn-xs delete-btn" ><i class="fa fa-trash"></i> Delete</button>'
								
							];
                        },
                    }
                ]
            });

        $(document).on("click",".delete-btn", function(){
            var self = this;
            var id = $(this).attr('data-id');
            var url = '{{ route('user.destroy',':id') }}'.replace(':id',id);

            dhtmlx.confirm({
                title: "Confirm Deletion",
                type: "confirm-warning",
                text: "Do you really want to delete this record?",
                callback: function(res){
                    if(!res){
                        return;
                    }
                    $.ajax({
                        type: "DELETE",
                        url: url,
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        success: function(response){
                            dhtmlx.alert({
                                title: 'Record Deleted',
                                text: 'The record has been successfully deleted',
                                callback: function() {
                                    dataTable.draw();
                                }
                            });
                        },
                        error: function(err){
                            alert("error");
                        }
                    });
                }
            });
        });
}); // end jQuery

        /**
        *  Delete record
        */
    
    </script>
@endsection