routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'web'], function () {

            Auth::routes();

            Route::group([
                'prefix' => '',
                'middleware' => ['auth']
                // 'middleware' => ['role:telco.*'],
            ], function() {
                    Route::resource('member', 'MemberController', [
                        'only' => ['index','create','store','edit','update','destroy']
                    ]);
                    Route::resource('user', 'UserController', [
                        'only' => ['index','create','store','edit','update','destroy']
                    ]);
                    Route::resource('testimony', 'TestimonyController');
                }
            );
        }
    );

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Member.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    protected $fillable = [
        'type_id',
        'title',
        'name',
        'gender',
        'date_saved',
        'address',
        'contact',
        'email',
        'birth_date',
        'occupation',
        'special_skill',
        'vices',
        'diseases'
    ];

    public function Type(){
        return $this->belongsTo(Type::class, 'type_id');
    }
}

app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Yajra\Datatables\Datatables;

use App\Member;
use App\Type;

class MemberController extends Controller
{

    /**
     * @param Member $member
     *
     */

    protected $member;

    public function __construct(Member $member){
        $this->member = $member;

        // $this->middleware('role:telco.admin', ['only' => ['create', 'store','edit','update','destroy']]);
        // $this->middleware('role:telco.admin|telco.user', ['only' => ['index']]);
    }

    /**
     * Display a listing of the resource.
     * @param Request $request
     * @return Response
     * 
     */
    public function index(Request $request)
	{   
        if($request->ajax()) {
            $member = $this->member->With('Type')->get();
            return Datatables::of($member)->make(true);
        }
        return view('pages.member.index');
    }

/**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Member $member){
        $type = Type::pluck('name','id')->reverse()->put('', '-----')->reverse();
        return view('pages.member.edit', compact('member', 'type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Member $member){
        $this->validate($request,[
            'type_id' => 'required',
            'name' => 'required',
            'gender' => 'required',
            'date_saved' => 'date',
            'address' => '',
            'contact' => '',
            'email' => 'email',
            'birth_date' => 'date',
            'occupation' => '',
            'special_skill' => '',
            'vices' => '',
            'diseases' => ''
        ]);
        $member->update($request->only([
            'type_id',
            'name',
            'gender',
            'date_saved',
            'address',
            'contact',
            'email',
            'birth_date',
            'occupation',
            'special_skill',
            'vices',
            'diseases'
        ]) );
        return view('pages.member.index');
    }

    /*
    *  open the form to create new resource
    *
    *
    */
    public function create(){
        $member = new Member();
        $type = Type::pluck('name','id')->reverse()->put('', '-----')->reverse();
        return view('pages.member.create', compact('member','type') );
    }

    /*
    *  store the newly created resource
    *
    *
    */
    public function store(Request $request, User $user){
        $this->validate($request,[
            'type_id' => 'required',
            'name' => 'required',
            'gender' => 'required',
            'date_saved' => 'date',
            'address' => '',
            'contact' => '',
            'email' => 'email',
            'birth_date' => 'date',
            'occupation' => '',
            'special_skill' => '',
            'vices' => '',
            'diseases' => ''
        ]);

        $user->create($request->only([
            'type_id',
            'name',
            'gender',
            'date_saved',
            'address',
            'contact',
            'email',
            'birth_date',
            'occupation',
            'special_skill',
            'vices',
            'diseases'
        ]) );
        return view('pages.member.index');
    }

    /*
    *  delete the selected resource
    *
    *
    */
    public function destroy(Member $member)
    {
        $member->delete();
        return response()->json([
			"success" => "true",
			"message" => "Member has been has been deleted.",
		]);
    }
}

resources/views/pages/member/create.blade.php
@extends('adminlte::page')

@section('title','JMCIM Webapp')

@section('content_header')
<h1>JMCIM <small>Add Member</small></h1>
@endsection

@section('content')
    <div class="box box-default">
        <div class="box-body">
            <div class="row">
                <div class="col-xs-12">
                    @include('layouts/error_box')
                    {{ Form::model($member, ['route' => ['member.store',$member->id], 'method' => 'POST', 'class' => 'form-horizontal'])}}
                    {{ csrf_field() }}

                    @include('pages.member.partials.forms')
                    <div class="form-group">
                        <div class="col-xs-1 col-xs-offset-2">
                            <button type="submit" class="btn btn-primary" placeholder"Submit"><i class="glyphicon glyphicon-check"></i> Save</button>
                        </div>
                        <div class="col-xs-1">
                            <a href="{{ route('member.index') }}" title="Cancel" class="btn btn-primary cancel_btn">
                            <i class="glyphicon glyphicon-remove-circle"></i> Cancel
                            </a>
                        </div>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
<script src="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.js') }}"></script>
<script src="{{ asset('js/helpers.js') }}"></script>
<script src="{{ asset('js/ajax-interceptor.js') }}"></script>

<script src="{{ asset('vendor/adminlte/plugins/datepicker/js/bootstrap-datepicker.min.js') }}"></script>
<script type="text/javascript">

    $(document).ready(function(){
        $('.datepicker').datepicker({
			format: 'yyyy-mm-dd'
        });
    });

</script>
@endsection

resources/views/pages/member/edit.blade.php
@extends('adminlte::page')

@section('title','JMCIM Webapp')

@section('content_header')
    <h1>JMCIM <small>Edit Member</small></h1>
@endsection

@section('css')
<link rel="stylesheet"
          href="{{ asset('css/app.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/fonts/font_roboto/roboto.css') }}">

@endsection

@section('content')    
<div class="box box-default">
        <div class="box-body">
            <div class="row">
                <div class="col-xs-12">
                    @include('layouts/error_box')
                    {{ Form::model($member, ['route' => ['member.update',$member->id], 'method' => 'PUT', 'class' => 'form-horizontal'])}}
                    {{ csrf_field() }}

                    @include('pages.member.partials.forms')
                    <div class="form-group">
                        <div class="col-xs-1 col-xs-offset-2">
                            <button type="submit" class="btn btn-primary" placeholder"Submit"><i class="glyphicon glyphicon-check"></i> Save</button>
                        </div>
                        <div class="col-xs-1">
                            <a href="{{ route('member.index') }}" title="Cancel" class="btn btn-primary cancel_btn">
                            <i class="glyphicon glyphicon-remove-circle"></i> Cancel
                            </a>
                        </div>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
<script src="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.js') }}"></script>
<script src="{{ asset('js/helpers.js') }}"></script>
<script src="{{ asset('js/ajax-interceptor.js') }}"></script>

<script src="{{ asset('vendor/adminlte/plugins/datepicker/js/bootstrap-datepicker.min.js') }}"></script>
<script type="text/javascript">

    $(document).ready(function(){
        $('.datepicker').datepicker({
			format: 'yyyy-mm-dd'
        });
    });

</script>
@endsection

resources/views/pages/member/index.blade.php
@extends('adminlte::page')

@section('title','JMCIM Webapp')

@section('content_header')
    <h1>JMCIM<small>Member</small></h1>
@endsection

@section('css')
    <link rel="stylesheet"
          href="{{ asset('css/app.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/fonts/font_roboto/roboto.css') }}">

@endsection

@section('content')
    <div class="box box-default">
        <div class="box-body">
            <div class="row">
                <div class="col-xs-12">
                    @include('layouts/error_box')

                    <a href="{{ route('member.create') }}" title="Add New" class="btn btn-primary btn-xs">
                        <i class="glyphicon glyphicon-plus"></i>Add New
                    </a>
                    <br></br>
                    <a href="#" data-action="{{url('testimony/5')}}" data-toggle="laramodal" class="btn btn-success btn-xs"><i class="glyphicon glyphicon-th-list"></i> Testimonies</a>
                    <br></br>

                    <div class="table-responsive">
                    <table class="table table-striped" id="data-table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Member Type</th>
                                <th>Name</th>
                                <th>Gender</th>
                                <th>Date Saved</th>
                                <!-- <th>Address</th> -->
                                <th>Contact</th>
                                <th>Email</th>
                                <th>Birth Date</th>
                                <!-- <th>Occupation</th>
                                <th>Special Skill</th>
                                <th>Vices</th>
                                <th>Diseases</th> -->
                                <th></th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script src="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.js') }}"></script>
    <script src="{{ asset('vendor/laramodal/laramodal.js')}}" ></script>
    <script type="text/javascript">
        $(document).ready(function(){
            var dataTable = $('#data-table').DataTable({
                processing: true,
                serverSide: true,
                deferRender: true,
                ajax: '{{ route("member.index") }}',
                columnDefs: [
                    {
                        'targets': 0,
                        'data': 'id',
                        'name': 'id',
                    },
                    {
                        'targets': 1,
                        'data': 'type.name',
                        'name': 'type.name',
                    },
                    {
                        'targets': 2,
                        'data': 'name',
                        'name': 'name',
                    },
                    {
                        'targets': 3,
                        'data': 'gender',
                        'name': 'gender',
                    },
                    {
                        'targets': 4,
                        'data': 'date_saved',
                        'name': 'date_saved',
                    },
                    // {
                    //     'targets': 5,
                    //     'data': 'address',
                    //     'name': 'address',
                    // },
                    {
                        'targets': 5,
                        'data': 'contact',
                        'name': 'contact',
                    },
                    {
                        'targets': 6,
                        'data': 'email',
                        'name': 'email',
                    },
                    {
                        'targets': 7,
                        'data': 'birth_date',
                        'name': 'birth_date',
                    },
                    // {
                    //     'targets': 9,
                    //     'data': 'occupation',
                    //     'name': 'occupation',
                    // },
                    // {
                    //     'targets': 10,
                    //     'data': 'special_skill',
                    //     'name': 'special_skill',
                    // },
                    // {
                    //     'targets': 11,
                    //     'data': 'vices',
                    //     'name': 'vices',
                    // },
                    // {
                    //     'targets': 12,
                    //     'data': 'diseases',
                    //     'name': 'diseases',
                    // },
                    {
                        'targets': 8,
                        'searchable': false,
                        'sortable': false,
                        'render': function(data,type,row){
                            var edit = '{{ route('member.edit',':id') }}'.replace(':id',row.id);
                            var show = '{{ route('testimony.show',':id') }}'.replace(':id',row.id);
                            
                           		return [
								'<a href="' + edit + '" title="Edit" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-edit"></i> Edit</a>' + " " +
                                '<button data-id="' + row.id + '" type="button" title="Delete" class="btn btn-danger btn-xs delete-btn" ><i class="fa fa-trash"></i> Delete</button>' + " " +
                                '<a href="#" data-action="' + show + '" data-toggle="laramodal" class="btn btn-success btn-xs"><i class="glyphicon glyphicon-th-list"></i> Testimonies</a>'
								
							];
                        },
                    }
                ]
            });

        $(document).on("click",".delete-btn", function(){
            var self = this;
            var id = $(this).attr('data-id');
            var url = '{{ route('member.destroy',':id') }}'.replace(':id',id);
            
            dhtmlx.confirm({
                title: "Confirm Deletion",
                type: "confirm-warning",
                text: "Do you really want to delete this record?",
                callback: function(res){
                    if(!res){
                        return;
                    }
                    $.ajax({
                        type: "DELETE",
                        url: url,
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        success: function(response){
                            dhtmlx.alert({
                                title: 'Record Deleted',
                                text: 'The record has been successfully deleted',
                                callback: function() {
                                    dataTable.draw();
                                }
                            });
                        },
                        error: function(err){
                            alert("error");
                        }
                    });
                }
            });
        });
}); // end jQuery
    
    </script>
@endsection